services:
  app:
    build:
      context: ./docker/node
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - ./app:/srv/app:rw,cached
      - ./public:/srv/app/public:rw,cached
    command: [ "npm", "run", "dev" ]
    env_file:
      - .env

  db:
    build:
      context: ./docker/mariadb
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app/public:/srv/app/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app